@echo off
echo Configuring MAKE for go32
rem This batch file assumes a unix-type "sed" program

update configh.dos config.h

echo # Makefile generated by "configure.bat"> Makefile

if exist config.sed del config.sed

echo ": try_sl						">> config.sed
echo "/\\$/ {						">> config.sed
echo "  N						">> config.sed
echo "  s/[ 	]*\\\n[ 	]*/ /			">> config.sed
echo "  b try_sl					">> config.sed
echo "}							">> config.sed

echo "s/@srcdir@/./					">> config.sed
echo "s/@CC@/gcc/					">> config.sed
echo "s/@CFLAGS@/-O2 -g/				">> config.sed
echo "s/@CPPFLAGS@/-DHAVE_CONFIG_H/			">> config.sed
echo "s/@LDFLAGS@//					">> config.sed
echo "s/@RANLIB@/ranlib/				">> config.sed
echo "s/@DEFS@//					">> config.sed
echo "s/@REMOTE@/stub/					">> config.sed
echo "s/@ALLOCA@//					">> config.sed
echo "s/@LIBS@//					">> config.sed
echo "s/@LIBOBJS@//					">> config.sed
echo "s/@SET_MAKE@//					">> config.sed
echo "s/^Makefile *:/_Makefile:/			">> config.sed
echo "s/^config.h *:/_config.h:/			">> config.sed
echo "s/^defines *=.*$/defines =/			">> config.sed
echo "/mv -f make.new make/d				">> config.sed

echo "s/cd glob; $(MAKE)/$(MAKE) -C glob/		">> config.sed

sed -e "s/^\"//" -e "s/\"$//" -e "s/[ 	]*$//" config.sed > config2.sed
sed -f config2.sed Makefile.in >> Makefile
del config.sed
del config2.sed

cd glob
call configure
cd ..
