Document: remake
Title: Debian remake Manual
Author: <insert document author here>
Abstract: This manual describes what remake is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/remake/remake.sgml.gz

Format: postscript
Files: /usr/share/doc/remake/remake.ps.gz

Format: text
Files: /usr/share/doc/remake/remake.text.gz

Format: HTML
Index: /usr/share/doc/remake/html/index.html
Files: /usr/share/doc/remake/html/*.html

  
