Document: remake-3.80+dbg
Title: Debian remake-3.80+dbg Manual
Author: <insert document author here>
Abstract: This manual describes what remake-3.80+dbg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/remake-3.80+dbg/remake-3.80+dbg.sgml.gz

Format: postscript
Files: /usr/share/doc/remake-3.80+dbg/remake-3.80+dbg.ps.gz

Format: text
Files: /usr/share/doc/remake-3.80+dbg/remake-3.80+dbg.text.gz

Format: HTML
Index: /usr/share/doc/remake-3.80+dbg/html/index.html
Files: /usr/share/doc/remake-3.80+dbg/html/*.html

  
