
# Run as ./make -f debug-test/Makefile -X --debugger-stop=preaction,
# then do `watch Hell.`.

UNEXPANDED=expanded

all: test
	echo "$(UNEXPANDED) all done!"

test:
	echo "$(UNEXPANDED) Hello"
	echo "$(UNEXPANDED) Goodbye"
