---
name: remake 4.4 (macos)

on:
  push:
    branches: [remake-4-4]
  pull_request:
    branches: [remake-4-4]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          brew install gcc pkg-config autoconf automake gettext readline guile texinfo texlive coreutils
      - name: Generate configure POSIX script
        run: autoreconf -i
      - name: Configure for GNU Make
        run: ./configure --enable-maintainer-mode CPPFLAGS="-I/opt/homebrew/opt/readline/include" LDFLAGS="-L/opt/homebrew/opt/readline/lib" LIBS="-lreadline -lhistory"
      - name: Pull localization files
        run: make po-update
      - name: Set up to rebuild doc
        run: (cd doc && make stamp-1 stamp-vti)
      - name: Run GNU make to build
      # FIXME: something is not right. Probably about the includes are picking up a wrong stat buffer that doesn't have mtim.
      # For now, we'll just turn say that we don't have nanosecond resolution.
        run: make CPPFLAGS="-UFILE_TIMESTAMP_HI_RES"

      - name: Test "remake" just built
        run: make check
      # - name: Check distribution building
      #   run: make distcheck
